export enum BlockchainNetwork {
  BSC = 'BSC',
  opBNB = 'opBNB',
}

export enum BlockchainToken {
  USDT = 'USDT',
  BNB = 'BNB',
}

export enum SettingKey {
  USDT_ADDRESS_OPBNB_NETWORK = 'USDT_ADDRESS_OPBNB_NETWORK',
  USDT_ADDRESS_BSC_NETWORK = 'USDT_ADDRESS_BSC_NETWORK',
  OPBNB_RPC_URL = 'OPBNB_RPC_URL',
  BSC_RPC_URL = 'BSC_RPC_URL',
  LUCKY_NUMBER_TODAY = 'LUCKY_NUMBER_TODAY',
  OVER_UNDER_MIN_AMOUNT = 'OVER_UNDER_MIN_AMOUNT',
  OVER_UNDER_MAX_AMOUNT = 'OVER_UNDER_MAX_AMOUNT',
  LUCKY_NUMBER_MIN_AMOUNT = 'LUCKY_NUMBER_MIN_AMOUNT',
  LUCKY_NUMBER_MAX_AMOUNT = 'LUCKY_NUMBER_MAX_AMOUNT',
  OVER_UNDER_MULTIPLIER = 'OVER_UNDER_MULTIPLIER',
  LUCKY_NUMBER_MULTIPLIER = 'LUCKY_NUMBER_MULTIPLIER',
}
