export enum BlockchainNetwork {
  BSC = 'BSC',
  OPBNB = 'OPBNB',
}

export enum BlockchainToken {
  USDT = 'USDT',
  BNB = 'BNB',
}

export enum SettingKey {
  USDT_ADDRESS_OPBNB_NETWORK = 'USDT_ADDRESS_OPBNB_NETWORK',
  USDT_ADDRESS_BSC_NETWORK = 'USDT_ADDRESS_BSC_NETWORK',
  OPBNB_RPC_URL = 'OPBNB_RPC_URL',
  BSC_RPC_URL = 'BSC_RPC_URL',
  LUCKY_NUMBER_TODAY = 'LUCKY_NUMBER_TODAY',
  ODD_EVEN_MIN_AMOUNT = 'ODD_EVEN_MIN_AMOUNT',
  ODD_EVEN_MAX_AMOUNT = 'ODD_EVEN_MAX_AMOUNT',
  LUCKY_NUMBER_MIN_AMOUNT = 'LUCKY_NUMBER_MIN_AMOUNT',
  LUCKY_NUMBER_MAX_AMOUNT = 'LUCKY_NUMBER_MAX_AMOUNT',
  ODD_MULTIPLIER = 'ODD_MULTIPLIER',
  EVEN_MULTIPLIER = 'EVEN_MULTIPLIER',
  LUCKY_NUMBER_MULTIPLIER = 'LUCKY_NUMBER_MULTIPLIER',
  ODD_EVEN_REF_MULTIPLIER = 'ODD_EVEN_REF_MULTIPLIER',
  LUCKY_NUMBER_REF_MULTIPLIER = 'LUCKY_NUMBER_REF_MULTIPLIER',
  TELE_BOT_INTRO_IMAGE = 'TELE_BOT_INTRO_IMAGE',
  TELE_BOT_OVER_UNDER_IMAGE = 'TELE_BOT_OVER_UNDER_IMAGE',
  TELE_BOT_LUCKY_NUMBER_IMAGE = 'TELE_BOT_LUCKY_NUMBER_IMAGE',
  TELE_MINI_APP_URL = 'TELE_MINI_APP_URL',
  TELE_CUSTOMER_SUPPORT_URL = 'TELE_CUSTOMER_SUPPORT_URL',
  TELEGRAM_ADMIN_CHAT_ID = 'TELEGRAM_ADMIN_CHAT_ID',

  ENABLE_USER_WITHDRAW = 'ENABLE_USER_WITHDRAW',
  WHITELIST_WALLET_WITHDRAW = 'WHITELIST_WALLET_WITHDRAW',
  MINIMUM_REF_WITHDRAW_AMOUNT = 'MINIMUM_REF_WITHDRAW_AMOUNT',

  ROTATE_ACCOUNT_MIN_WITHDRAW_AMOUNT = 'ROTATE_ACCOUNT_MIN_WITHDRAW_AMOUNT',
  ROTATE_ACCOUNT_MIN_USED_IN_MINUTE = 'ROTATE_ACCOUNT_MIN_USED_IN_MINUTE',

  POOL_ADDRESS = 'POOL_ADDRESS',

  ENABLE_LOTTERY_1 = 'ENABLE_LOTTERY_1',
  ENABLE_LOTTERY_2 = 'ENABLE_LOTTERY_2',
  ENABLE_LOTTERY_3 = 'ENABLE_LOTTERY_3',

  LOTTERY_1_MIN_AMOUNT = 'LOTTERY_1_MIN_AMOUNT',
  LOTTERY_1_MAX_AMOUNT = 'LOTTERY_1_MAX_AMOUNT',
  LOTTERY_1_JACKPOT_MULTIPLIER = 'LOTTERY_1_JACKPOT_MULTIPLIER',
  LOTTERY_1_REF_MULTIPLIER = 'LOTTERY_1_REF_MULTIPLIER',

  LOTTERY_2_MIN_AMOUNT = 'LOTTERY_2_MIN_AMOUNT',
  LOTTERY_2_MAX_AMOUNT = 'LOTTERY_2_MAX_AMOUNT',
  LOTTERY_2_JACKPOT_MULTIPLIER = 'LOTTERY_2_JACKPOT_MULTIPLIER',
  LOTTERY_2_REF_MULTIPLIER = 'LOTTERY_2_REF_MULTIPLIER',

  LOTTERY_3_MIN_AMOUNT = 'LOTTERY_3_MIN_AMOUNT',
  LOTTERY_3_MAX_AMOUNT = 'LOTTERY_3_MAX_AMOUNT',
  LOTTERY_3_JACKPOT_MULTIPLIER = 'LOTTERY_3_JACKPOT_MULTIPLIER',
  LOTTERY_3_REF_MULTIPLIER = 'LOTTERY_3_REF_MULTIPLIER',

  OVER_UNDER_MIN_AMOUNT = 'OVER_UNDER_MIN_AMOUNT',
  OVER_UNDER_MAX_AMOUNT = 'OVER_UNDER_MAX_AMOUNT',
  OVER_MULTIPLIER = 'OVER_MULTIPLIER',
  UNDER_MULTIPLIER = 'UNDER_MULTIPLIER',
  OVER_UNDER_REF_MULTIPLIER = 'OVER_UNDER_REF_MULTIPLIER',
  ENABLE_OVER_UNDER = 'ENABLE_OVER_UNDER',

  ORDER_PREFIX = 'ORDER_PREFIX',
}
